services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AWLSolutions\EzPlatformContribBundle\FieldType\RichText\FieldValueConverterDecorator:
        decorates: EzSystems\EzPlatformRichText\eZ\Persistence\Legacy\RichTextFieldValueConverter
        arguments:
            $richTextFieldValueConverter: '@AWLSolutions\EzPlatformContribBundle\FieldType\RichText\FieldValueConverterDecorator.inner'
